### ISSUE TITLE
Nonetype object

### ISSUE THREAD

**Issue by Pusherman2** [9homme/awesome-bot#1]
Hi there,

I am getting the following error on an initial launch:
`current state for None datetime: None position: None price: None quantity: None exit_price: None take_profit: None total_revenue: None
Some error occured but just skip, message: 'NoneType' object has no attribute 'lower'`

All settings are default with only API keys and telegram ID added.

Do you maybe have an idea how/why I am getting this error?

Kind regards,

Pusherman

**Comment by 9homme** [comment]
@Pusherman2 Hi, I think my last commit will fix this issue
sorry about this.
