### ISSUE TITLE
ticker = XXXX

### ISSUE THREAD

**Issue by concu72** [9homme/awesome-bot#5]
I noticed that when auto_scouting = true is selected in the user.cfg file, it ignores the coin named XXXX in the ticker = XXXX line in the same file, that is, it does not transact for this coin.
If the ticker = section is left blank, this time the bot will not start processing at all.
If auto_scouting = true, the coin named XXXX in ticker = XXXX must also be added to the all_coins_list = line.
I don't know if this is a problem but I noticed something like this.

**Comment by 9homme** [comment]
yes, this is current behavior for the bot.
`all_coins_list` need to contain all the coins you want to trade.
